<a href="https://colab.research.google.com/github/jahnavitelsang/Assignment2026/blob/main/Hypothesis_testing_assignment6_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd
from math import sqrt
from scipy.stats import t
from scipy.stats import norm
from scipy.stats import stats
import statsmodels
import warnings
warnings.filterwarnings('ignore')

In [27]:
#Data
# A total of 15 print-heads were randomly selected and tested until failure. The durability of each print-head (in millions of characters) was recorded as follows:
# 1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29

In [28]:
data = [1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]
data = pd.DataFrame(data)
data

       0
0   1.13
1   1.55
2   1.43
3   0.92
4   1.25
5   1.36
6   1.32
7   0.85
8   1.07
9   1.48
10  1.20
11  1.33
12  1.18
13  1.22
14  1.29

In [29]:
n = len(data)
n

15

In [30]:
stddata = data.std()
stddata

0    0.193164
dtype: float64

In [31]:
meandata=data.mean()
meandata

0    1.238667
dtype: float64

In [32]:
#a. Build 99% Confidence Interval Using Sample Standard Deviation

In [33]:
# As the population standard deviation is not known and the sample size is also small that is just 15 , we use t-distribution.
# Now also calculate the standard of error 1st

In [34]:
std_error = stddata/(sqrt(n))
std_error

0    0.049875
dtype: float64

In [35]:
# As the stand of error is calculated , lets find the t values
t_value = t.ppf(0.995, n-1)      # n-1 is the degree of freedom which is df and is calculated as 14 in this case
t_value

np.float64(2.976842734370834)

In [36]:
# now lets calucalte the margin of error
margin_of_error = t_value*std_error
margin_of_error

0    0.148469
dtype: float64

In [37]:
# Now for the confidence interval there is a rangle which is mean+-Margin pf error which means

In [38]:
print("99% CI using t-distribution:")
print((meandata - margin_of_error, meandata + margin_of_error))
# the output shows that it is 99% confident that the range lies between 1.090197 - 1.387136

99% CI using t-distribution:
(0    1.090197
dtype: float64, 0    1.387136
dtype: float64)

In [39]:
#b. Build 99% Confidence Interval Using Known Population Standard Deviation

In [40]:
# Since the population std deviation is known that is 0.2 we are using z- distribution .

In [41]:
# lets calculate the standard of error .
std_error2 = 0.2 / (sqrt(n))
std_error2

0.051639777949432225

In [42]:
# now lets calculate z value
z_value = norm.ppf(0.995)
z_value

np.float64(2.5758293035489004)

In [43]:
# The margin of error is
margin_of_error2 = z_value*std_error2
margin_of_error2

np.float64(0.13301525327090588)

In [44]:
# Now the CI is
print('CI using z- distribution is :')
print((meandata + margin_of_error, meandata - margin_of_error2))

CI using z- distribution is :
(0    1.387136
dtype: float64, 0    1.105651
dtype: float64)

In [45]:
# So now the output lies between  1.106 million and 1.372 million characters with teh std of 0.2

In [46]:
#Hypothesis testing

In [47]:
#Statement
# NULL HYPOTHESIS(H0)= Pop_mean is 4000 and alternate hypothesis(ha) = pop_mean is greater than 4000

In [48]:
### Given Data
pop_mean = 1000 + (5 * 600)
pop_std_dev = 5 * 25
n = 25
x_bar = 3050

In [49]:
# Null statis - Z-score

In [50]:
standard_error = pop_std_dev / np.sqrt(n)
z_score = (x_bar - pop_mean) / standard_error

In [51]:
z_score

np.float64(-38.0)

In [52]:
# Probability

In [58]:
alpha=0.05 # 5% significance level
z_critical = norm.ppf(1 - alpha)
z_critical

np.float64(1.6448536269514722)

In [59]:
z_critical < z_score

np.False_

In [ ]:
# DECISION
#  z_critical< s_score is false

In [54]:
# CONCLUSION - The data provides no proof to back up the restaurant owners' assertion, indicating that actual weekly operating expenses do not exceed the model's projections.
# Why? The previous model estimates expenses at Rs. 4,000, whereas the owners' real average cost is just Rs. 3,050.

# Result: Since their actual expenses (3,050) fall below the model's prediction (4,000), the owners' grievance is unfounded, meaning the existing cost model remains completely reliable.